#Number of redis servers, could not use an integer like client, because redis servers need host and port
servers:
  -
    "rnode0.in:6379"
  -
    "rnode1.in:6379"
  -
    "rnode2.in:6379"
  -
    "rnode3.in:6389"
  -
    "rnode4.in:6389"

#If not able to run actual redis servers, set mock to true
mock: false

#Number of clients, upto 12 clients can be added(To stimulate)
numberofclients: 3

#Choose any one from three partitions [rack, region, rack+region]. Add a new type of partition in partitions.go
partitiontype: rack

#Number of messages to be sent at a time
messages: 1

#Simulate with a failed redis node ?
failanyredis: true

failredisnodes:
  -
    "rnode1.in:6379"
  -
    "rnode2.in:6379"


#Output messages
debug: true
