#Number of redis servers, could not use numbers, because redis servers need host and port
servers:
  -
    "rnode0.in:6379"
  -
    "rnode1.in:6379"
  -
    "rnode2.in:6379"
  -
    "rnode3.in:6389"
  -
    "rnode4.in:6389"

#If not able to run actual redis servers, set mock to true
mock: true

#Number of clients
numberofclients: 8

#Choose any one from three partitions [rack, region, rack+region]. Add a new type of partition in partitions.go
partitiontype: rack

#Number of messages to be sent at a time
messages: 1

#Simulate with a failed redis node ?
failanyredis: true
#Choose a number starting from 0 to (n-1) where n is total number of redis servers.
#this node will be unreachable to all the clients. Only one node could be failed 
failredisnode: 3

#Output messages
debug: true
